INSERT INTO TBA_INSTRUMENT (NM_INSTRUMENT)
	VALUES
	('Violino'),
	('Viola'),
	('Violoncelo'),
	('Orgão Eletrônico'),
	('Flauta'),
	('Clarinete'),
	('Oboé'),
	('Corne Inglês'),
	('Fagote'),
	('Clarone-Mib'),
	('Clarone-Sib'),
	('Soprano Reto-Sib'),
	('Soprano Curvo-Sib'),
	('Alto-Mib'),
	('Tenor-Sib'),
	('Barítono-Mib'),
	('Trompete'),
	('Cornet'),
	('Flugelhorn'),
	('Melofone'),
	('Trompa-Fá/Sib'),
	('Tuba Wagneriana'),
	('Trombone-Sib'),
	('Trombone-Dó'),
	('Trombonito'),
	('Barítono'),
	('Bombardino'),
	('Tuba');