DELIMITER //
CREATE PROCEDURE GET_INSTRUMENTS_BY_FILTER(IN P_ID_INSTRUMENT INT, IN P_NM_INSTRUMENT VARCHAR(255))
BEGIN
    SELECT * FROM TBA_INSTRUMENT
	WHERE 1 = 1
	AND ID_INSTRUMENT = COALESCE(P_ID_INSTRUMENT, ID_INSTRUMENT)
	AND UPPER(NM_INSTRUMENT) LIKE UPPER(COALESCE(CONCAT('%' , P_NM_INSTRUMENT , '%'), NM_INSTRUMENT));
END //
DELIMITER ;
