DELIMITER //
CREATE PROCEDURE GET_STATES_BY_FILTER(IN P_ID_STATE INT, IN P_DE_STATE VARCHAR(255))
BEGIN
    SELECT * FROM tbd_state
	WHERE 1 = 1
	AND ID_STATE = COALESCE(P_ID_STATE, ID_STATE)
	AND UPPER(DE_STATE) LIKE UPPER(COALESCE(CONCAT('%' , P_DE_STATE , '%'), DE_STATE));
END //
DELIMITER ;
