INSERT INTO TBD_CHURCH (DE_CHURCH)
	VALUES
	('Jardim Santa Bárbara'),
	('Jardim Eliana'),
	('Macedo'),
	('Jardim Pinhal'),
	('Bom Clima'),
	('Vila Barros'),
	('Jardim Almeida Prado'),
	('Jardim Alvorada'),
	('Centro'),
	('Jardim Jovaia'),
	('Jardim Bela Vista'),
	('Vila São João Batista'),
	('Bairro Dos Morros Votorantim'),
	('Jardim Adriana'),
	('Jardim Marilena'),
	('Jardim Santa Rita'),
	('Jardim São Paulo'),
	('Jardim Rosa de França'),
	('Vila Cisper');