CREATE TABLE TBD_EVENT_ATTENDEES (
	ID_EVENT_ATTENDEES int NOT NULL AUTO_INCREMENT,
    ID_EVENT int NOT NULL,
    ID_CHURCH int NOT NULL,
    ID_ATTENDEE_TYPE int,
    ID_INSTRUMENT int,
    PRIMARY KEY (ID_EVENT_ATTENDEES)
);