ALTER TABLE `ccb`.`tbd_event_attendees` 
ADD CONSTRAINT `ID_EVENT`
  FOREIGN KEY (`ID_EVENT`)
  REFERENCES `ccb`.`tbd_event` (`ID_EVENT`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `ID_CHURCH`
  FOREIGN KEY (`ID_CHURCH`)
  REFERENCES `ccb`.`tbd_church` (`ID_CHURCH`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `ID_ATTENDEE_TYPE`
  FOREIGN KEY (`ID_ATTENDEE_TYPE`)
  REFERENCES `ccb`.`tba_attendee_type` (`ID_ATTENDEE_TYPE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `ID_INSTRUMENT`
  FOREIGN KEY (`ID_INSTRUMENT`)
  REFERENCES `ccb`.`tba_instrument` (`ID_INSTRUMENT`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
