DELIMITER // 

CREATE PROCEDURE INSERT_TBD_EVENT_ATTENDEES(
	IN P_ID_EVENT_ATTENDEES INT, 
    IN P_ID_EVENT INT,
    IN P_ID_CHURCH INT, 
    IN P_ID_ATTENDEE_TYPE INT,
    IN P_ID_INSTRUMENT INT
    )
BEGIN
	INSERT INTO tbd_event_attendees(
		ID_EVENT_ATTENDEES, 
		ID_EVENT, 
		ID_CHURCH, 
		ID_ATTENDEE_TYPE, 
		ID_INSTRUMENT
		) 
    VALUES (
		P_ID_EVENT_ATTENDEES, 
		P_ID_EVENT, 
		IFNULL(P_ID_CHURCH, NULL), 
		P_ID_ATTENDEE_TYPE, 
		IFNULL(P_ID_INSTRUMENT, NULL)
		);
END //
    
DELIMITER // ;