DELIMITER // 

Create PROCEDURE INSERT_TBD_EVENT(
	IN P_ID_EVENT INT, 
    IN P_NM_EVENT VARCHAR(255),
    IN P_DT_EVENT DATETIME, 
    IN P_ID_EVENT_TYPE VARCHAR(255)
    )
BEGIN
	INSERT INTO tbd_event(ID_EVENT, NM_EVENT, DT_EVENT, ID_EVENT_TYPE) 
    VALUES (P_ID_EVENT, P_NM_EVENT, P_DT_EVENT, P_ID_EVENT_TYPE);
END //
    
DELIMITER // ;